name: disstans-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.11
  - numpy>=1.26
  - pandas>=2.1
  - scipy>=1.11
  - scikit-learn>=1.3
  - matplotlib>=3.8
  - cartopy>=0.22
  - owslib
  - cmcrameri
  - cvxpy>=1.3
  - cvxopt
  - tqdm
  - sqlalchemy
  - ffmpeg
  - jupyterlab  # optional
  - sphinx>=5.3  # optional
  - docutils  # optional
  - doc8  # optional
  - rstcheck  # optional
  - flake8  # optional
  - build  # optional
  - twine  # optional
  - sphinx-rtd-theme  # optional
  - sphinx-autodoc-typehints  # optional
  - pygmt  # optional
  - pip
  - pip:
    - git+https://github.com/tbenthompson/okada_wrapper.git
    - git+https://github.com/sphinx-contrib/video.git  # optional
