name: disstans
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.11
  - numpy>=1.25
  - pandas>=2.0
  - scipy>=1.11
  - scikit-learn>=1.3
  - matplotlib>=3.7
  - cartopy>=0.21
  - owslib
  - cmcrameri
  - cvxpy>=1.3
  - cvxopt
  - tqdm
  - sqlalchemy
  - ffmpeg
  - pip
  - pip:
    - git+https://github.com/tbenthompson/okada_wrapper.git
