name: disstans-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.12
  - numpy>=1.26
  - pandas>=2.1
  - scipy>=1.11
  - scikit-learn>=1.3
  - matplotlib>=3.8
  - cartopy>=0.22
  - owslib
  - cmcrameri
  - cvxpy>=1.3
  - tqdm
  - sqlalchemy
  - ffmpeg
  - pip
  - jupyterlab  # optional
  - sphinx>=5.3  # optional
  - docutils  # optional
  - doc8  # optional
  - rstcheck  # optional
  - ruff  # optional
  - build  # optional
  - twine  # optional
  - sphinx-rtd-theme  # optional
  - sphinx-autodoc-typehints  # optional
  - pygmt  # optional
  - pip:
    - okada-wrapper>=24.6.15  # required for disstans.earthquakes okada functions
    - sphinxcontrib-video  # optional
