name: disstans-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.9
  - numpy>=1.22
  - pandas>=1
  - scipy>=1.6
  - scikit-learn>=1.1
  - matplotlib>=3.5
  - cartopy>=0.20
  - owslib
  - cmcrameri
  - cvxpy>=1
  - cvxopt
  - tqdm
  - sqlalchemy
  - ffmpeg
  - jupyterlab  # optional
  - sphinx>=4  # optional
  - docutils  # optional
  - doc8  # optional
  - rstcheck  # optional
  - flake8  # optional
  - build  # optional
  - twine  # optional
  - pip
  - pip:
    - git+https://github.com/tbenthompson/okada_wrapper.git
    - sphinx-rtd-theme  # optional
    - git+https://github.com/sphinx-contrib/video.git  # optional
